//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiClicker.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string ActionColumn {
            get {
                return ResourceManager.GetString("ActionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files (*.*).
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MultiClicker.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto complete HDV (see position config) --&gt;.
        /// </summary>
        internal static string AutoCompleteHDV {
            get {
                return ResourceManager.GetString("AutoCompleteHDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Background.
        /// </summary>
        internal static string ChangeBackground {
            get {
                return ResourceManager.GetString("ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✖.
        /// </summary>
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        internal static string ClearColumn {
            get {
                return ResourceManager.GetString("ClearColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CLICK with Delay.
        /// </summary>
        internal static string ClickWithDelay {
            get {
                return ResourceManager.GetString("ClickWithDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click without Delay.
        /// </summary>
        internal static string ClickWithoutDelay {
            get {
                return ResourceManager.GetString("ClickWithoutDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string ColorColumn {
            get {
                return ResourceManager.GetString("ColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration saved successfully!.
        /// </summary>
        internal static string ConfigSavedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dofus Havenbag.
        /// </summary>
        internal static string DOFUS_HAVENBAG {
            get {
                return ResourceManager.GetString("DOFUS_HAVENBAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dofus Open Discussion.
        /// </summary>
        internal static string DOFUS_OPEN_DISCUSSION {
            get {
                return ResourceManager.GetString("DOFUS_OPEN_DISCUSSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double Click (No delay).
        /// </summary>
        internal static string DOUBLE_CLICK {
            get {
                return ResourceManager.GetString("DOUBLE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error opening keyboard shortcuts configuration: {0}.
        /// </summary>
        internal static string ErrorOpeningKeybinds {
            get {
                return ResourceManager.GetString("ErrorOpeningKeybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill HDV.
        /// </summary>
        internal static string FILL_HDV {
            get {
                return ResourceManager.GetString("FILL_HDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FUNCTION ----&gt; Bind.
        /// </summary>
        internal static string FunctionBind {
            get {
                return ResourceManager.GetString("FunctionBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group Characters.
        /// </summary>
        internal static string GROUP_CHARACTERS {
            get {
                return ResourceManager.GetString("GROUP_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ?.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Files.
        /// </summary>
        internal static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input chat commands.
        /// </summary>
        internal static string InputChatCommands {
            get {
                return ResourceManager.GetString("InputChatCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keybinds.
        /// </summary>
        internal static string Keybinds {
            get {
                return ResourceManager.GetString("Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⌨.
        /// </summary>
        internal static string KeybindsButton {
            get {
                return ResourceManager.GetString("KeybindsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard Shortcuts Configuration.
        /// </summary>
        internal static string KeybindsFormTitle {
            get {
                return ResourceManager.GetString("KeybindsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on a field then press keys and/or click with the mouse (left, right, middle, X1, X2) to define the shortcut. The initial click is not recorded..
        /// </summary>
        internal static string KeybindsInstructions {
            get {
                return ResourceManager.GetString("KeybindsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard Shortcuts Configuration.
        /// </summary>
        internal static string KeybindsTooltip {
            get {
                return ResourceManager.GetString("KeybindsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  (Enter to confirm, Escape to cancel).
        /// </summary>
        internal static string KeyCombinationInstruction {
            get {
                return ResourceManager.GetString("KeyCombinationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language changed successfully. Please restart the application for all changes to take effect..
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next character.
        /// </summary>
        internal static string NextCharacter {
            get {
                return ResourceManager.GetString("NextCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste on All Windows.
        /// </summary>
        internal static string PASTE_ON_ALL_WINDOWS {
            get {
                return ResourceManager.GetString("PASTE_ON_ALL_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste on all windows.
        /// </summary>
        internal static string PasteOnAllWindows {
            get {
                return ResourceManager.GetString("PasteOnAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string PositionColumn {
            get {
                return ResourceManager.GetString("PositionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positions&apos; config.
        /// </summary>
        internal static string PositionsConfig {
            get {
                return ResourceManager.GetString("PositionsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press keys and/or click....
        /// </summary>
        internal static string PressKeysPrompt {
            get {
                return ResourceManager.GetString("PressKeysPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Character.
        /// </summary>
        internal static string PreviousCharacter {
            get {
                return ResourceManager.GetString("PreviousCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready to capture....
        /// </summary>
        internal static string ReadyToCapture {
            get {
                return ResourceManager.GetString("ReadyToCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to reset all shortcuts?.
        /// </summary>
        internal static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Next Character.
        /// </summary>
        internal static string SELECT_NEXT {
            get {
                return ResourceManager.GetString("SELECT_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Previous Character.
        /// </summary>
        internal static string SELECT_PREVIOUS {
            get {
                return ResourceManager.GetString("SELECT_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Background Image.
        /// </summary>
        internal static string SelectBackgroundImage {
            get {
                return ResourceManager.GetString("SelectBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shortcut.
        /// </summary>
        internal static string ShortcutColumn {
            get {
                return ResourceManager.GetString("ShortcutColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simple Click.
        /// </summary>
        internal static string SIMPLE_CLICK {
            get {
                return ResourceManager.GetString("SIMPLE_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simple Click (No Delay).
        /// </summary>
        internal static string SIMPLE_CLICK_NO_DELAY {
            get {
                return ResourceManager.GetString("SIMPLE_CLICK_NO_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travel.
        /// </summary>
        internal static string TRAVEL {
            get {
                return ResourceManager.GetString("TRAVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trigger Name.
        /// </summary>
        internal static string TriggerNameColumn {
            get {
                return ResourceManager.GetString("TriggerNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string UpdateColumn {
            get {
                return ResourceManager.GetString("UpdateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
